<template>
    <div>
       <ul>
            <li>首页</li>
            <li>分类</li>
            <li>发现</li>
            <li>购物车</li>
            <li>个人中心</li>
       </ul>
    </div>
</template>